### ISSUE TITLE
❓ How to remove specific rows of a dataset ?

### ISSUE THREAD

**Issue by Colanim** [huggingface/nlp#117]
I saw on the [example notebook](https://colab.research.google.com/github/huggingface/nlp/blob/master/notebooks/Overview.ipynb#scrollTo=efFhDWhlvSVC) how to remove a specific column :

```python
dataset.drop('id')
```

But I didn't find how to remove a specific row. 

**For example, how can I remove all sample with `id` < 10 ?**

**Comment by thomwolf** [comment]
Hi, you can't do that at the moment.

**Comment by Shaowen310** [comment]
Maybe, you can use `filter` https://huggingface.co/docs/datasets/processing.html#filtering-rows-select-and-filter

**Comment by zellsophia** [comment]
Can you do it by now? Coz it would be awfully helpful!

**Comment by zellsophia** [comment]
That's what I ended up doing too. but it feels like a workaround to a feature that should be added to the datasets class.
