### ISSUE TITLE
❓ How to apply a map to all subsets ?

### ISSUE THREAD

**Issue by Colanim** [huggingface/nlp#118]
I'm working with CNN/DM dataset, where I have 3 subsets : `train`, `test`, `validation`.

Should I apply my map function on the subsets one by one ?

```python
import nlp

cnn_dm = nlp.load_dataset('cnn_dailymail')
for corpus in ['train', 'test', 'validation']:
        cnn_dm[corpus].map(my_func)
```

Or is there a better way to do this ?

**Comment by thomwolf** [comment]
That's the way!
