### ISSUE TITLE
Error with sklearn train_test_split

### ISSUE THREAD

**Issue by ClonedOne** [huggingface/nlp#147]
It would be nice if we could use sklearn `train_test_split` to quickly generate subsets from the dataset objects returned by `nlp.load_dataset`. At the moment the code:

```python
data = nlp.load_dataset('imdb', cache_dir=data_cache)
f_half, s_half = train_test_split(data['train'], test_size=0.5, random_state=seed)
```
throws:
```
ValueError: Can only get row(s) (int or slice) or columns (string).
```
It's not a big deal, since there are other ways to split the data, but it would be a cool thing to have.

**Comment by thomwolf** [comment]
Indeed. Probably we will want to have a similar method directly in the library

**Comment by KappaDistributive** [comment]
Related: #166
