### ISSUE TITLE
[Feature request] Add Ubuntu Dialogue Corpus dataset

### ISSUE THREAD

**Issue by AlphaMycelium** [huggingface/nlp#149]
https://github.com/rkadlec/ubuntu-ranking-dataset-creator or http://dataset.cs.mcgill.ca/ubuntu-corpus-1.0/

**Comment by mariamabarham** [comment]
@AlphaMycelium the Ubuntu Dialogue Corpus [version 2]( https://github.com/rkadlec/ubuntu-ranking-dataset-creator) is added. Note that it requires a manual download by following the download instructions in the [repos]( https://github.com/rkadlec/ubuntu-ranking-dataset-creator).
Maybe we can close this issue for now?
