### ISSUE TITLE
nlp.load_dataset() gives "TypeError: list_() takes exactly one argument (2 given)"

### ISSUE THREAD

**Issue by saahiluppal** [huggingface/nlp#157]
I'm trying to load datasets from nlp but there seems to have error saying 
"TypeError: list_() takes exactly one argument (2 given)"

gist can be found here
https://gist.github.com/saahiluppal/c4b878f330b10b9ab9762bc0776c0a6a

**Comment by patrickvonplaten** [comment]
You can just run: 
`val = nlp.load_dataset('squad')` 

if you want to have just the validation script you can also do:

`val = nlp.load_dataset('squad', split="validation")`

**Comment by patrickvonplaten** [comment]
If you want to load a local dataset, make sure you include a `./` before the folder name.

**Comment by Mistobaan** [comment]
This happens by just doing run all cells on colab ... I assumed the colab example is broken.

**Comment by patrickvonplaten** [comment]
Oh I see you might have a wrong version of pyarrow install on the colab -> could you try the following. Add these lines to the beginning of your notebook, restart the runtime and run it again:
```
!pip uninstall -y -qq pyarrow
!pip uninstall -y -qq nlp
!pip install -qq git+https://github.com/huggingface/nlp.git
```

**Comment by Sharvil97** [comment]
> Oh I see you might have a wrong version of pyarrow install on the colab -> could you try the following. Add these lines to the beginning of your notebook, restart the runtime and run it again:
> 
> ```
> !pip uninstall -y -qq pyarrow
> !pip uninstall -y -qq nlp
> !pip install -qq git+https://github.com/huggingface/nlp.git
> ```

Tried, having the same error.

**Comment by patrickvonplaten** [comment]
Can you post a link here of your colab? I'll make a copy of it and see what's wrong

**Comment by thomwolf** [comment]
This should be fixed in the current version of the notebook. You can try it again

**Comment by patrickvonplaten** [comment]
Also see: https://github.com/huggingface/nlp/issues/222

**Comment by parthplc** [comment]
I am getting this error when running this command
```
val = nlp.load_dataset('squad', split="validation")
```

FileNotFoundError: [Errno 2] No such file or directory: '/root/.cache/huggingface/datasets/squad/plain_text/1.0.0/dataset_info.json'

Can anybody help?

**Comment by patrickvonplaten** [comment]
It seems like your download was corrupted :-/ Can you run the following command: 

```
rm -r /root/.cache/huggingface/datasets
```

to delete the cache completely and rerun the download?

**Comment by Mistobaan** [comment]
I tried the notebook again today and it worked without barfing. 👌
