### ISSUE TITLE
Add Spanish POR and NER Datasets

### ISSUE THREAD

**Issue by mrm8488** [huggingface/nlp#164]
Hi guys,
In order to cover multilingual support a little step could be adding standard Datasets used for Spanish NER and POS tasks.
I can provide it in raw and preprocessed formats.

**Comment by thomwolf** [comment]
Hello @mrm8488, are these datasets official datasets published in an NLP/CL/ML venue?

**Comment by mrm8488** [comment]
What about this one: https://github.com/ccasimiro88/TranslateAlignRetrieve?
