### ISSUE TITLE
Add a method to shuffle a dataset

### ISSUE THREAD

**Issue by thomwolf** [huggingface/nlp#166]
Could maybe be a `dataset.shuffle(generator=None, seed=None)` signature method.

Also, we could maybe have a clear indication of which method modify in-place and which methods return/cache a modified dataset. I kinda like torch conversion of having an underscore suffix for all the methods which modify a dataset in-place. What do you think?

**Comment by Colanim** [comment]
+1 for the naming convention

About the `shuffle` method, from my understanding it should be done in `Dataloader` (better separation between dataset processing - usage)

**Comment by richardyy1188** [comment]
+1 for shuffle in `Dataloader`. 
Some `Dataloader` just store idxs of dataset and just shuffle those idxs, which might(?) be faster than do shuffle in dataset, especially when doing shuffle every epoch.

Also +1 for the naming convention.

**Comment by vblagoje** [comment]
As you might already know the issue of dataset shuffling came up in the nlp code [walkthrough](https://youtu.be/G3pOvrKkFuk?t=3204) by Yannic Kilcher

**Comment by lhoestq** [comment]
We added the `.shuffle` method :)

Closing this one.
