### ISSUE TITLE
Clone not working on Windows environment

### ISSUE THREAD

**Issue by codehunk628** [huggingface/nlp#172]
Cloning in a windows environment is not working because of use of special character '?' in folder name ..
Please consider changing the folder name ....
Reference to folder -
nlp/datasets/cnn_dailymail/dummy/3.0.0/3.0.0/dummy_data-zip-extracted/dummy_data/uc?export=download&id=0BwmD_VLjROrfM1BxdkxVaTY2bWs/dailymail/stories/

error log:
fatal: cannot create directory at 'datasets/cnn_dailymail/dummy/3.0.0/3.0.0/dummy_data-zip-extracted/dummy_data/uc?export=download&id=0BwmD_VLjROrfM1BxdkxVaTY2bWs': Invalid argument

**Comment by lhoestq** [comment]
Should be fixed on master now :)

**Comment by codehunk628** [comment]
Thanks @lhoestq 👍  Now I can uninstall WSL and get back to work with windows.🙂
