### ISSUE TITLE
Weird-ish: Not creating unique caches for different phases

### ISSUE THREAD

**Issue by zphang** [huggingface/nlp#186]
Sample code:

```python
import nlp
dataset = nlp.load_dataset('boolq')

def func1(x):
    return x

def func2(x):
    return None

train_output = dataset["train"].map(func1)
valid_output = dataset["validation"].map(func1)
print()
print(len(train_output), len(valid_output))
# Output: 9427 9427
```

The map method in both cases seem to be pointing to the same cache, so the latter call based on the validation data will return the processed train data cache.

What's weird is that the following doesn't seem to be an issue:

```python
train_output = dataset["train"].map(func2)
valid_output = dataset["validation"].map(func2)
print()
print(len(train_output), len(valid_output))
# 9427 3270
```

**Comment by lhoestq** [comment]
Looks like a duplicate of #120.
This is already fixed on master. We'll do a new release on pypi soon

**Comment by zphang** [comment]
Good catch, it looks fixed.
