### ISSUE TITLE
When will the remaining math_dataset modules be added as dataset objects

### ISSUE THREAD

**Issue by tylerroost** [huggingface/nlp#188]
Currently only the algebra_linear_1d is supported. Is there a timeline for making the other modules supported. If no timeline is established, how can I help?

**Comment by tylerroost** [comment]
On a similar note it would be nice to differentiate between train-easy, train-medium, and train-hard

**Comment by thomwolf** [comment]
Hi @tylerroost, we don't have a timeline for this at the moment.
If you want to give it a look we would be happy to review a PR on it.
Also, the library is one week old so everything is quite barebones, in particular the doc.
You should expect some bumps on the road.

To get you started, you can check the datasets scripts in the `./datasets` folder on the repo and find the one on math_datasets that will need to be modified. Then you should check the original repository on the math_dataset to see where the other files to download are located and what is the expected format for the various parts of the dataset.

To get a general overview on how datasets scripts are written and used, you can read the nice tutorial on how to add a new dataset for TensorFlow Dataset [here](https://www.tensorflow.org/datasets/add_dataset), our API is not exactly identical but it can give you a high-level overview.

**Comment by tylerroost** [comment]
Thanks I'll give it a look
