### ISSUE TITLE
Index outside of table length

### ISSUE THREAD

**Issue by casajarm** [huggingface/nlp#198]
The offset input box warns of numbers larger than a limit (like 2000) but then the errors start at a smaller value than that limit (like 1955).

> ValueError: Index (2000) outside of table length (2000).
> Traceback:
> File "/home/sasha/.local/lib/python3.7/site-packages/streamlit/ScriptRunner.py", line 322, in _run_script
>     exec(code, module.__dict__)
> File "/home/sasha/nlp_viewer/run.py", line 116, in <module>
>     v = d[item][k]
> File "/home/sasha/.local/lib/python3.7/site-packages/nlp/arrow_dataset.py", line 338, in __getitem__
>     output_all_columns=self._output_all_columns,
> File "/home/sasha/.local/lib/python3.7/site-packages/nlp/arrow_dataset.py", line 290, in _getitem
>     raise ValueError(f"Index ({key}) outside of table length ({self._data.num_rows}).")

**Comment by lhoestq** [comment]
Interesting. Could you provide a snippet of code to reproduce this error ?

**Comment by lhoestq** [comment]
Sounds like something related to the nlp viewer @srush

**Comment by srush** [comment]
Fixed.
