### ISSUE TITLE
[Question] Combine 2 datasets which have the same columns

### ISSUE THREAD

**Issue by airKlizz** [huggingface/nlp#206]
Hi,

I am using ``nlp`` to load personal datasets. I created summarization datasets in multi-languages based on wikinews. I have one dataset for english and one for german (french is getting to be ready as well). I want to keep these datasets independent because they need different pre-processing (add different task-specific prefixes for T5 : *summarize:* for english and *zusammenfassen:* for german)

My issue is that I want to train T5 on the combined english and german datasets to see if it improves results. So I would like to combine 2 datasets (which have the same columns) to make one and train T5 on it. I was wondering if there is a proper way to do it? I assume that it can be done by combining all examples of each dataset but maybe you have a better solution.

Hoping this is clear enough,

Thanks a lot 😊
Best

**Comment by lhoestq** [comment]
We are thinking about ways to combine datasets for T5 in #217, feel free to share your thoughts about this.

**Comment by airKlizz** [comment]
Ok great! I will look at it. Thanks
