### ISSUE TITLE
Should we still have to force to install apache_beam to download wikipedia ?

### ISSUE THREAD

**Issue by richardyy1188** [huggingface/nlp#227]
Hi, first thanks to @lhoestq 's revolutionary work, I successfully downloaded processed wikipedia according to the doc. 😍😍😍

But at the first try, it tell me to install `apache_beam` and `mwparserfromhell`, which I thought wouldn't be used according to #204 , it was kind of confusing me at that time.

Maybe we should not force users to install these ? Or we just add them to`nlp`'s dependency ?

**Comment by lhoestq** [comment]
Thanks for your message 😊 
Indeed users shouldn't have to install those dependencies

**Comment by richardyy1188** [comment]
Got it, feel free to close this issue when you think it’s resolved.

**Comment by lhoestq** [comment]
It should be good now :)
