### ISSUE TITLE
What is the best way to cache a dataset? 

### ISSUE THREAD

**Issue by Mistobaan** [huggingface/nlp#246]
For example if I want to use streamlit with a nlp dataset:

```
@st.cache
def load_data():
    return nlp.load_dataset('squad')
```
This code raises the error "uncachable object"

Right now I just fixed with a constant for my specific case:
```
    @st.cache(hash_funcs={pyarrow.lib.Buffer: lambda b: 0})
```
But I was curious to know what is the best way in general

**Comment by thomwolf** [comment]
Everything is already cached by default in 🤗nlp (in particular dataset
loading and all the “map()” operations) so I don’t think you need to do any
specific caching in streamlit.

Tell us if you feel like it’s not the case.

**Comment by lhoestq** [comment]
Closing this one. Feel free to re-open if you have other questions !
