### ISSUE TITLE
[Feature request] Be able to remove a specific sample of the dataset

### ISSUE THREAD

**Issue by Colanim** [huggingface/nlp#254]
As mentioned in #117, it's currently not possible to remove a sample of the dataset.

But it is a important use case : After applying some preprocessing, some samples might be empty for example. We should be able to remove these samples from the dataset, or at least mark them as `removed` so when iterating the dataset, we don't iterate these samples.

I think it should be a feature. What do you think ?

---

Any work-around in the meantime ?

**Comment by thomwolf** [comment]
Oh yes you can now do that with the `dataset.filter()` method that was added in #214
