### ISSUE TITLE
[Feature request] Add a feature to dataset

### ISSUE THREAD

**Issue by sarahwie** [huggingface/nlp#256]
Is there a straightforward way to add a field to the arrow_dataset, prior to performing map?

**Comment by thomwolf** [comment]
Do you have an example of what you would like to do? (you can just add a field in the output of the unction you give to map and this will add this field in the output table)

**Comment by sarahwie** [comment]
Given another source of data loaded in, I want to pre-add it to the dataset so that it aligns with the indices of the arrow dataset prior to performing map.

E.g. 
```
new_info = list of length dataset['train']

dataset['train'] = dataset['train'].map(lambda x: some_function(x, new_info[index of x]))

def some_function(x, new_info_x):
    # adds new_info[index of x] as a field to x
    x['new_info'] = new_info_x
    return x
```
I was thinking to instead create a new field in the arrow dataset so that instance x contains all the necessary information when map function is applied (since I don't have index information to pass to map function).

**Comment by sarahwie** [comment]
This is what I have so far: 

```
import pyarrow as pa
from nlp.arrow_dataset import Dataset

aug_dataset = dataset['train'][:]
aug_dataset['new_info'] = new_info

#reformat as arrow-table
schema = dataset['train'].schema

# this line doesn't work:
schema.append(pa.field('new_info', pa.int32()))

table = pa.Table.from_pydict(
    aug_dataset,
    schema=schema
)
dataset['train'] = Dataset(table) 
```

**Comment by thomwolf** [comment]
Maybe you can use `with_indices`?

```python
new_info = list of length dataset['train']

def some_function(indice, x):
    # adds new_info[index of x] as a field to x
    x['new_info'] = new_info_x[indice]
    return x

dataset['train'] = dataset['train'].map(some_function, with_indices=True)
```

**Comment by sarahwie** [comment]
Oh great. That should work. I missed that in the documentation- thanks :)
