### ISSUE TITLE
Empty samples in glue/qqp

### ISSUE THREAD

**Issue by richardyy1188** [huggingface/nlp#277]
```
qqp = nlp.load_dataset('glue', 'qqp')
print(qqp['train'][310121])
print(qqp['train'][362225])
```
```
{'question1': 'How can I create an Android app?', 'question2': '', 'label': 0, 'idx': 310137}
{'question1': 'How can I develop android app?', 'question2': '', 'label': 0, 'idx': 362246}
```
Notice that question 2 is empty string. 
BTW, I have checked and these two are the only naughty ones in all splits of qqp.

**Comment by thomwolf** [comment]
We are only wrapping the original dataset.

Maybe try to ask on the GLUE mailing list or reach out to the original authors?

**Comment by richardyy1188** [comment]
Tanks for the suggestion, I'll try to ask GLUE benchmark.
I'll first close the issue,  post the following up here afterwards, and reopen the issue if needed.
