### ISSUE TITLE
snli -1 labels

### ISSUE THREAD

**Issue by jxmorris12** [huggingface/nlp#296]
I'm trying to train a model on the SNLI dataset. Why does it have so many -1 labels?
```
import nlp
from collections import Counter
data = nlp.load_dataset('snli')['train']
print(Counter(data['label']))
Counter({0: 183416, 2: 183187, 1: 182764, -1: 785})
```

**Comment by mariamabarham** [comment]
@jxmorris12  , we use `-1` to label examples for which `gold label`  is missing (`gold label = -` in the original dataset).

**Comment by jxmorris12** [comment]
Thanks @mariamabarham! so the original dataset is missing some labels? That is weird. Is standard practice just to discard those examples training/eval?

**Comment by mariamabarham** [comment]
Yes the original dataset is missing some labels maybe  @sleepinyourhat , @gangeli can correct me if I'm wrong 
For my personal opinion at least if you want your model to learn to predict no answer (-1) you can leave it their but otherwise you can discard them.

**Comment by jxmorris12** [comment]
thanks @mariamabarham  :)
