### ISSUE TITLE
🐛 [Metrics] ROUGE is non-deterministic

### ISSUE THREAD

**Issue by Colanim** [huggingface/nlp#361]
If I run the ROUGE metric 2 times, with same predictions / references, the scores are slightly different.

Refer to [this Colab notebook](https://colab.research.google.com/drive/1wRssNXgb9ldcp4ulwj-hMJn0ywhDOiDy?usp=sharing) for reproducing the problem.

Example of F-score for ROUGE-1, ROUGE-2, ROUGE-L in 2 differents run :

> ['0.3350', '0.1470', '0.2329']
['0.3358', '0.1451', '0.2332']

---

Why ROUGE is not deterministic ?

**Comment by thomwolf** [comment]
Hi, can you give a full self-contained example to reproduce this behavior?

**Comment by lhoestq** [comment]
> Hi, can you give a full self-contained example to reproduce this behavior?

There is a notebook in the post ;)

**Comment by lhoestq** [comment]
> If I run the ROUGE metric 2 times, with same predictions / references, the scores are slightly different.
> 
> Refer to [this Colab notebook](https://colab.research.google.com/drive/1wRssNXgb9ldcp4ulwj-hMJn0ywhDOiDy?usp=sharing) for reproducing the problem.
> 
> Example of F-score for ROUGE-1, ROUGE-2, ROUGE-L in 2 differents run :
> 
> > ['0.3350', '0.1470', '0.2329']
> > ['0.3358', '0.1451', '0.2332']
> 
> Why ROUGE is not deterministic ?

This is because of rouge's `BootstrapAggregator` that uses sampling to get confidence intervals (low, mid, high).
You can get deterministic scores per sentence pair by using
```python
score = rouge.compute(rouge_types=["rouge1", "rouge2", "rougeL"], use_agregator=False)
```

**Comment by lhoestq** [comment]
Maybe we can set all the random seeds of numpy/torch etc. while running `metric.compute` ?

**Comment by thomwolf** [comment]
We should probably indeed!

**Comment by lhoestq** [comment]
Now if you re-run the notebook, the two printed results are the same:
```
['0.3356', '0.1466', '0.2318']
['0.3356', '0.1466', '0.2318']
```
However across sessions, the results may change (as numpy's random seed can be different). You can prevent that by setting your seed:
```python
rouge = nlp.load_metric('rouge', seed=42)
```

**Comment by lxuechen** [comment]
> 

Minor nit: Note that "aggregator" is misspelled in this command. Should be `use_aggregator=False`.

**Comment by lhoestq** [comment]
Thanks, I fixed the code snippet
