### ISSUE TITLE
from_dict delete?

### ISSUE THREAD

**Issue by hackerxiaobai** [huggingface/nlp#414]
AttributeError: type object 'Dataset' has no attribute 'from_dict'

**Comment by lhoestq** [comment]
`from_dict` was added in #350 that was unfortunately not included in the 0.3.0 release. It's going to be included in the next release that will be out pretty soon though.
Right now if you want to use `from_dict` you have to install the package from the master branch
```
pip install git+https://github.com/huggingface/nlp.git
```

**Comment by hackerxiaobai** [comment]
> `from_dict` was added in #350 that was unfortunately not included in the 0.3.0 release. It's going to be included in the next release that will be out pretty soon though.
> Right now if you want to use `from_dict` you have to install the package from the master branch
> 
> ```
> pip install git+https://github.com/huggingface/nlp.git
> ```
OK, thank you.
