### ISSUE TITLE
[FEATURE REQUEST] Multiprocessing with for dataset.map, dataset.filter

### ISSUE THREAD

**Issue by timothyjlaurent** [huggingface/nlp#426]
It would be nice to be able to speed up `dataset.map` or `dataset.filter`. Perhaps this is as easy as sharding the dataset sending each shard to a process/thread/dask pool and using the new `nlp.concatenate_dataset()` function to join them all together?

**Comment by lhoestq** [comment]
Yes that's definitely something we plan to add ^^

**Comment by thomwolf** [comment]
Yes, that would be nice. We could take a look at what tensorflow `tf.data` does under the hood for instance.

**Comment by timothyjlaurent** [comment]
So `tf.data.Dataset.map()` returns a `ParallelMapDataset` if `num_parallel_calls is not None` [link](https://github.com/tensorflow/tensorflow/blob/2b96f3662bd776e277f86997659e61046b56c315/tensorflow/python/data/ops/dataset_ops.py#L1623).

There, `num_parallel_calls` is turned into a tensor and and fed to `gen_dataset_ops.parallel_map_dataset` where it looks like tensorflow takes over.

We could start with something simple like a thread or process pool that `imap`s over some shards.

**Comment by lhoestq** [comment]
Multiprocessing was added in #552 . You can set the number of processes with `.map(..., num_proc=...)`. It also works for `filter`

Closing this one, but feel free to reo-open if you have other questions

**Comment by Chen-Hailin** [comment]
@lhoestq Great feature implemented! Do you have plans to add it to official tutorials [Processing data in a Dataset](https://huggingface.co/docs/datasets/processing.html?highlight=save#augmenting-the-dataset)? It took me sometime to find this parallel processing api.

**Comment by lhoestq** [comment]
Thanks for the heads up !

I just added a paragraph about multiprocessing:
https://huggingface.co/docs/datasets/master/processing.html#multiprocessing
