### ISSUE TITLE
ImportWarning for pyarrow 1.0.0

### ISSUE THREAD

**Issue by HanGuo97** [huggingface/nlp#435]
The following PR raised ImportWarning at `pyarrow ==1.0.0` https://github.com/huggingface/nlp/pull/265/files

**Comment by lhoestq** [comment]
This was fixed in #434 
We'll do a release later this week to include this fix.
Thanks for reporting

**Comment by Ierezell** [comment]
I dont know if the fix was made but the problem is still present : 
Instaled with pip : NLP 0.3.0 // pyarrow 1.0.0 
OS : archlinux with kernel zen 5.8.5

**Comment by thomwolf** [comment]
Yes it was fixed in `nlp>=0.4.0`
You can update with pip

**Comment by Ierezell** [comment]
Sorry, I didn't got the updated version, all is working perfectly
