### ISSUE TITLE
Google Colab - load_dataset - PyArrow exception

### ISSUE THREAD

**Issue by nsankar** [huggingface/nlp#436]
With latest PyArrow 1.0.0 installed, I get the following exception   . Restarting colab has the same issue

ImportWarning: To use `nlp`, the module `pyarrow>=0.16.0` is required, and the current version of `pyarrow` doesn't match this condition. If you are running this in a Google Colab, you should probably just restart the runtime to use the right version of `pyarrow`.

The error goes only when I install version 0.16.0 
i.e.  !pip install pyarrow==0.16.0

**Comment by thomwolf** [comment]
Indeed, we’ll make a new PyPi release next week to solve this. Cc @lhoestq

**Comment by jxmorris12** [comment]
+1! this is the reason our tests are failing at [TextAttack](https://github.com/QData/TextAttack) 

(Though it's worth noting if we fixed the version number of pyarrow to 0.16.0 that would fix our problem too. But in this case we'll just wait for you all to update)

**Comment by svenski** [comment]
Came to raise this issue, great to see other already have and it's being fixed so soon!

As an aside, since no one wrote this already, it seems like the version check only looks at the second part of the version number making sure it is >16, but pyarrow newest version is 1.0.0 so the second past is 0!

**Comment by lhoestq** [comment]
> Indeed, we’ll make a new PyPi release next week to solve this. Cc @lhoestq

Yes definitely

**Comment by jxmorris12** [comment]
please fix this! @lhoestq

**Comment by Murgates** [comment]
Is this issue fixed ?

**Comment by thomwolf** [comment]
We’ll release the new version later today. Apologies for the delay.

**Comment by lhoestq** [comment]
I just pushed the new version on pypi :)

**Comment by nsankar** [comment]
Thanks for the update.
