### ISSUE TITLE
rotten tomatoes movie review dataset taken down

### ISSUE THREAD

**Issue by jxmorris12** [huggingface/nlp#483]
In an interesting twist of events, the individual who created the movie review seems to have left Cornell, and their webpage has been removed, along with the movie review dataset (http://www.cs.cornell.edu/people/pabo/movie-review-data/rt-polaritydata.tar.gz). It's not downloadable anymore.

**Comment by jxmorris12** [comment]
found a mirror: https://storage.googleapis.com/seldon-datasets/sentence_polarity_v1/rt-polaritydata.tar.gz

**Comment by jxmorris12** [comment]
fixed in #484

**Comment by lhoestq** [comment]
Closing this one. Thanks again @jxmorris12 for taking care of this :)
