### ISSUE TITLE
No 0.4.0 release on GitHub

### ISSUE THREAD

**Issue by jarednielsen** [huggingface/nlp#491]
0.4.0 was released on PyPi, but not on GitHub. This means [the documentation](https://huggingface.co/nlp/) is still displaying from 0.3.0, and that there's no tag to easily clone the 0.4.0 version of the repo.

**Comment by lhoestq** [comment]
I did the release on github, and updated the doc :)
Sorry for the delay

**Comment by jarednielsen** [comment]
Thanks!
