### ISSUE TITLE
Version of numpy to use the library

### ISSUE THREAD

**Issue by isspek** [huggingface/nlp#510]
Thank you so much for your excellent work! I would like to use nlp library in my project. While importing nlp, I am receiving the following error `AttributeError: module 'numpy.random' has no attribute 'Generator'` Numpy version in my project is 1.16.0. May I learn which numpy version is used for the nlp library.

Thanks in advance.

**Comment by thomwolf** [comment]
Seems like this method was added in 1.17. I'll add a requirement on this.

**Comment by isspek** [comment]
Thank you so much. After upgrading the numpy library, it worked.
