### ISSUE TITLE
nlp re-creates already-there caches when using a script, but not within a shell

### ISSUE THREAD

**Issue by TevenLeScao** [huggingface/nlp#580]
`nlp` keeps creating new caches for the same file when launching `filter` from a script, and behaves correctly from within the shell.

Example: try running

```
import nlp

hans_easy_data = nlp.load_dataset('hans', split="validation").filter(lambda x: x['label'] == 0)
hans_hard_data = nlp.load_dataset('hans', split="validation").filter(lambda x: x['label'] == 1)
```

twice. If launched from a `file.py` script, the cache will be re-created the second time. If launched as 3 shell/`ipython` commands, `nlp` will correctly re-use the cache.
As observed with @lhoestq.

**Comment by lhoestq** [comment]
Couln't reproduce on my side :/ 
let me know if you manage to reproduce on another env (colab for example)

**Comment by TevenLeScao** [comment]
Fixed with a clean re-install!
