### ISSUE TITLE
Indices incorrect with multiprocessing

### ISSUE THREAD

**Issue by joeddav** [huggingface/nlp#597]
When `num_proc` > 1, the indices argument passed to the map function is incorrect:

```python
d = load_dataset('imdb', split='test[:1%]')

def fn(x, inds):
    print(inds)
    return x

d.select(range(10)).map(fn, with_indices=True, batched=True)
# [0, 1]
# [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

d.select(range(10)).map(fn, with_indices=True, batched=True, num_proc=2)
# [0, 1]
# [0, 1]
# [0, 1, 2, 3, 4]
# [0, 1, 2, 3, 4]
```

As you can see, the subset passed to each thread is indexed from 0 to N which doesn't reflect their positions in `d`.

**Comment by lhoestq** [comment]
I fixed a bug that could cause this issue earlier today. Could you pull the latest version and try again ?

**Comment by thomwolf** [comment]
Still the case on master. I guess we should have an offset in the multi-procs indeed (hopefully it's enough).
